"""empty message

Revision ID: 84dd1773e632
Revises: 8f4d3f797602
Create Date: 2023-12-27 12:34:43.964832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84dd1773e632'
down_revision: Union[str, None] = '8f4d3f797602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('musics', sa.Column('artist_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'musics', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musics', type_='foreignkey')
    op.drop_column('musics', 'artist_id')
    op.alter_column('artists', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
