"""empty message

Revision ID: b436b95cdca4
Revises: d855cd7b6578
Create Date: 2023-12-28 14:16:58.616902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b436b95cdca4'
down_revision: Union[str, None] = 'd855cd7b6578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token', sa.VARCHAR(length=1000), nullable=False))
    op.add_column('tokens', sa.Column('refresh_token', sa.VARCHAR(length=1000), nullable=False))
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_column('tokens', 'refresh_token')
    op.drop_column('tokens', 'access_token')
    # ### end Alembic commands ###
