"""empty message

Revision ID: cd6318dfd177
Revises: 85146cf238da
Create Date: 2023-12-29 11:15:43.323489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd6318dfd177'
down_revision: Union[str, None] = '85146cf238da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'refresh_token',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'refresh_token',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
